service: lambda-nodejs-sample

provider:
  name: aws
  runtime: nodejs8.x

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true

functions:
  - '${file(api/sample/serverless.yml)}'

plugins:
  - serverless-webpack
  - serverless-offline
